{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-k8s-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: kubernetes-apps
      rules:
        # Alerte pour les pods qui crashent fréquemment
        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Pod crashing multiple times
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} is restarting frequently

        # Alerte pour les pods bloqués en état Pending
        - alert: PodStuckInPending
          expr: kube_pod_status_phase{phase="Pending"} == 1
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: Pod stuck in Pending state
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in pending state for more than 30 minutes

    - name: memory-alerts
      rules:
        # Alerte pour utilisation élevée de la mémoire
        - alert: HighMemoryUsage
          expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 85
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: High memory usage detected
            description: Container {{ $labels.container }} in pod {{ $labels.pod }} is using more than 85% of its memory limit

    - name: node-alerts
      rules:
        # Alerte pour nœud presque plein
        - alert: NodeDiskAlmostFull
          expr: disk_used_percent > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Node disk almost full
            description: Node {{ $labels.instance }} disk usage is {{ $value }}%

    - name: kafka-alerts
      rules:
        # Alerte pour les topics Kafka en retard
        - alert: KafkaTopicLag
          expr: kafka_consumergroup_lag > 10000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Kafka consumer group lag
            description: Consumer group {{ $labels.consumergroup }} on topic {{ $labels.topic }} is lagging by {{ $value }} messages

    - name: service-alerts
      rules:
        # Alerte pour les erreurs HTTP
        - alert: HighErrorRate
          expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: High HTTP error rate
            description: Service {{ $labels.service }} has a {{ $value }}% error rate

    - name: database-alerts
      rules:
        # Alerte pour les connexions PostgreSQL
        - alert: PostgresqlHighConnections
          expr: pg_stat_activity_count > 100
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High number of PostgreSQL connections
            description: Database {{ $labels.database }} has {{ $value }} active connections
{{- end }}