kube-prometheus-stack:

  prometheusOperator:
    enabled: true
    createCustomResourceDefinitions: true
    admissionWebhooks:
      enabled: false
    tls:
      enabled: false
    serviceMonitor:
      selfMonitor: true

  prometheus:
    enabled: true
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels:
          # release: prometheus-stack 
          app.kubernetes.io/part-of: kube-prometheus-stack
      ruleSelector:                # Ajout important
        matchLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      serviceMonitorNamespaceSelector: {}  # Ajout important
      ruleNamespaceSelector: {}           # Ajout important
      retention: 15d
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

  grafana:
    enabled: true
    adminPassword: admin
    persistence:
      enabled: true
      size: 10Gi

    # Ajout de la configuration du sidecar pour les dashboards
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
        defaultFolderName: "General"
        provider:
          folder: "General"
    
    # Le reste de votre configuration Grafana...
    plugins:
      - grafana-piechart-panel
      - grafana-clock-panel

    notifiers:
      default:
        name: email-notifier
        type: email
        uid: email1

    securityContext:
      runAsUser: 472
      runAsGroup: 472
      fsGroup: 472

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.local
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"

serviceMonitors:
  kafka:
    enabled: true