# values.yaml
prometheus:
  alertmanager:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
    
  server:
    persistentVolume:
      enabled: true
      size: 50Gi
    
    retention: "30d"
    
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    
  nodeExporter:
    enabled: true
    
  pushgateway:
    enabled: true
    
  kubeStateMetrics:
    enabled: true